### ISSUE TITLE
Database Design

### ISSUE THREAD

**Issue by justin123yu** [sfsu-csc-667-fall-2023/team-term-project-group-h#14]
Created a database design to be implemented.

**Comment by RINO-GAELICO** [comment]
1. We need a way to keep track of the points within the hand or section. Right now we have points in game_users table and that one can refer to the game itself, but within the section or hand you are playing there is also a counter of how many points you made so far (basically the hearts you get plus the queen of spades I believe). So probably one more column in game_user.

2. We need the FK from game_states and games tables.

3. We probably need one more column in the game_states for the dominant seed (the seed that started that hand)

4. Professor was saying to take advantage of zeros and negative numbers in the card_order for indicating:
a. if the card was discarded (probably -1)
b. if the card was on the table (probably 0)
We should decide how to deal with that aspect and write it down somewhere so that once we go to implement we have a reference and we are all on the same page.
